# @package agent
_target_: agent.deviation.DeviationAgent
name: deviation
domain: ${domain}
reward_free: ${reward_free}
obs_type: ??? # to be specified later
obs_shape: ??? # to be specified later
action_shape: ??? # to be specified later
device: ${device}
lr: 1e-4
critic_target_tau: 0.01
update_every_steps: 2
use_tb: ${use_tb}
use_wandb: ${use_wandb}
num_expl_steps: ??? # to be specified later
hidden_dim: 1024
feature_dim: 50
stddev_schedule: 0.2
stddev_clip: 0.3
skill_dim: 16
update_skill_every_step: 50
nstep: 3
batch_size: 1024
init_critic: true
update_encoder: ${update_encoder}
num_init_frames: 4000
scale: 0.1

ensemble_size: 16    # 16 for default setting

# extra hyperparameter
weight: 1.5
explor_rate: {"walker": 0.04, "quadruped": 0.04, "jaco": 2}
latent_dim: 40
temperature: 1

# skill finetuning ablation
skill: -1
